/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package se.kth.iv1351.openapi;

import se.kth.iv1351.openapi.model.Booking;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-01-02T14:10:17.421652+02:00[Europe/Mariehamn]")
@Validated
@Api(value = "booking", description = "the booking API")
public interface BookingApi {

    default BookingApiDelegate getDelegate() {
        return new BookingApiDelegate() {};
    }

    /**
     * GET /booking/{bookingid}
     * Returns a booking
     *
     * @param bookingid  (required)
     * @return Successful response (status code 200)
     */
    @ApiOperation(value = "", nickname = "bookingBookingidGet", notes = "Returns a booking", response = Booking.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = Booking.class) })
    @GetMapping(
        value = "/booking/{bookingid}",
        produces = { "application/json" }
    )
    default ResponseEntity<Booking> bookingBookingidGet(@ApiParam(value = "",required=true) @PathVariable("bookingid") Integer bookingid) {
        return getDelegate().bookingBookingidGet(bookingid);
    }


    /**
     * POST /booking
     * Lets a user post a new booking
     *
     * @param booking  (required)
     * @return Successfully created a new booking (status code 200)
     *         or Invalid request (status code 400)
     */
    @ApiOperation(value = "", nickname = "bookingPost", notes = "Lets a user post a new booking", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully created a new booking"),
        @ApiResponse(code = 400, message = "Invalid request") })
    @PostMapping(
        value = "/booking",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> bookingPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Booking booking) {
        return getDelegate().bookingPost(booking);
    }

}
