/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package se.kth.iv1351.openapi;

import se.kth.iv1351.openapi.model.RentalInstrument;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-01-06T10:18:36.432578+02:00[Europe/Mariehamn]")
@Validated
@Api(value = "rentalinstrument", description = "the rentalinstrument API")
public interface RentalinstrumentApi {

    default RentalinstrumentApiDelegate getDelegate() {
        return new RentalinstrumentApiDelegate() {};
    }

    /**
     * POST /rentalinstrument
     * Lets a user post a new rental instrument
     *
     * @param rentalInstrument  (required)
     * @return Successfully created a new rental instrument (status code 200)
     *         or Invalid request (status code 400)
     */
    @ApiOperation(value = "", nickname = "rentalinstrumentPost", notes = "Lets a user post a new rental instrument", response = RentalInstrument.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully created a new rental instrument", response = RentalInstrument.class),
        @ApiResponse(code = 400, message = "Invalid request") })
    @PostMapping(
        value = "/rentalinstrument",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<RentalInstrument> rentalinstrumentPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody RentalInstrument rentalInstrument) {
        return getDelegate().rentalinstrumentPost(rentalInstrument);
    }


    /**
     * DELETE /rentalinstrument/{rentalid}
     * Deletes a rental instrument
     *
     * @param rentalid  (required)
     * @return Successful delete (status code 200)
     */
    @ApiOperation(value = "", nickname = "rentalinstrumentRentalidDelete", notes = "Deletes a rental instrument", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful delete") })
    @DeleteMapping(
        value = "/rentalinstrument/{rentalid}"
    )
    default ResponseEntity<Void> rentalinstrumentRentalidDelete(@ApiParam(value = "",required=true) @PathVariable("rentalid") Integer rentalid) {
        return getDelegate().rentalinstrumentRentalidDelete(rentalid);
    }


    /**
     * GET /rentalinstrument/{rentalid}
     * Returns a rental instrument
     *
     * @param rentalid  (required)
     * @return Successful response (status code 200)
     */
    @ApiOperation(value = "", nickname = "rentalinstrumentRentalidGet", notes = "Returns a rental instrument", response = RentalInstrument.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = RentalInstrument.class) })
    @GetMapping(
        value = "/rentalinstrument/{rentalid}",
        produces = { "application/json" }
    )
    default ResponseEntity<RentalInstrument> rentalinstrumentRentalidGet(@ApiParam(value = "",required=true) @PathVariable("rentalid") Integer rentalid) {
        return getDelegate().rentalinstrumentRentalidGet(rentalid);
    }


    /**
     * PUT /rentalinstrument/{rentalid}
     * updates a rental instrument
     *
     * @param rentalid  (required)
     * @param rentalInstrument  (required)
     * @return Successful response (status code 200)
     */
    @ApiOperation(value = "", nickname = "rentalinstrumentRentalidPut", notes = "updates a rental instrument", response = RentalInstrument.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = RentalInstrument.class) })
    @PutMapping(
        value = "/rentalinstrument/{rentalid}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<RentalInstrument> rentalinstrumentRentalidPut(@ApiParam(value = "",required=true) @PathVariable("rentalid") Integer rentalid,@ApiParam(value = "" ,required=true )  @Valid @RequestBody RentalInstrument rentalInstrument) {
        return getDelegate().rentalinstrumentRentalidPut(rentalid, rentalInstrument);
    }

}
