/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package se.kth.iv1351.openapi;

import se.kth.iv1351.openapi.model.RentalInstrument;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-01-02T12:42:42.850804+02:00[Europe/Mariehamn]")
@Validated
@Api(value = "rentalinstrument", description = "the rentalinstrument API")
public interface RentalinstrumentApi {

    default RentalinstrumentApiDelegate getDelegate() {
        return new RentalinstrumentApiDelegate() {};
    }

    /**
     * GET /rentalinstrument/{rentalid}
     * Returns a rental instrument
     *
     * @param rentalid  (required)
     * @return Successful response (status code 200)
     */
    @ApiOperation(value = "", nickname = "rentalinstrumentRentalidGet", notes = "Returns a rental instrument", response = RentalInstrument.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = RentalInstrument.class) })
    @GetMapping(
        value = "/rentalinstrument/{rentalid}",
        produces = { "application/json" }
    )
    default ResponseEntity<RentalInstrument> rentalinstrumentRentalidGet(@ApiParam(value = "",required=true) @PathVariable("rentalid") Integer rentalid) {
        return getDelegate().rentalinstrumentRentalidGet(rentalid);
    }

}
