/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package se.kth.iv1351.openapi;

import se.kth.iv1351.openapi.model.UserApplication;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-01-02T12:42:42.850804+02:00[Europe/Mariehamn]")
@Validated
@Api(value = "userapplication", description = "the userapplication API")
public interface UserapplicationApi {

    default UserapplicationApiDelegate getDelegate() {
        return new UserapplicationApiDelegate() {};
    }

    /**
     * GET /userapplication/{applicationid}
     * Returns a user application
     *
     * @param applicationid  (required)
     * @return Successful response (status code 200)
     */
    @ApiOperation(value = "", nickname = "userapplicationApplicationidGet", notes = "Returns a user application", response = UserApplication.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = UserApplication.class) })
    @GetMapping(
        value = "/userapplication/{applicationid}",
        produces = { "application/json" }
    )
    default ResponseEntity<UserApplication> userapplicationApplicationidGet(@ApiParam(value = "",required=true) @PathVariable("applicationid") Integer applicationid) {
        return getDelegate().userapplicationApplicationidGet(applicationid);
    }

}
