openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
servers:
  - url: https://soundgood.music/
paths:
  /user/{userid}:
    get:
      description: Returns a user
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /user:
    post:
      description: Lets a user post a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        '200':
          description: Successfully created a new user

        '400':
          description: Invalid request



components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        personNumber:
          type: string
        age:
          type: integer
        email:
          type: string