openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
servers:
  - url: https://soundgood.music/
paths:
  /user/{userid}:
    get:
      description: Returns a user
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /user:
    post:
      description: Lets a user post a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        '200':
          description: Successfully created a new user

        '400':
          description: Invalid request
  /booking/{bookingid}:
    get:
      description: Returns a booking
      parameters:
        - name: bookingid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
  /booking:
    post:
      description: Lets a user post a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Booking"

      responses:
        '200':
          description: Successfully created a new booking

        '400':
          description: Invalid request
  /instrumenttype/{instrumentid}:
    get:
      description: Returns a instrument type
      parameters:
        - name: instrumentid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InstrumentType"
  /instrumenttype:
    post:
      description: Lets a user post a new instrument type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InstrumentType"

      responses:
        '200':
          description: Successfully created a new instrument type

        '400':
          description: Invalid request
  /lease/{leaseid}:
    get:
      description: Returns a lease
      parameters:
        - name: leaseid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lease"
  /lease:
    post:
      description: Lets a user post a new lease
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Lease"

      responses:
        '200':
          description: Successfully created a new lease

        '400':
          description: Invalid request
  /lesson/{lessonid}:
    get:
      description: Returns a lesson
      parameters:
        - name: lessonid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lesson"
  /lesson:
    post:
      description: Lets a user post a new lesson
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Lesson"

      responses:
        '200':
          description: Successfully created a new lesson

        '400':
          description: Invalid request
  /parent/{parentid}:
    get:
      description: Returns a parent
      parameters:
        - name: parentid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Parent"
  /parent:
    post:
      description: Lets a user post a new parent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Parent"

      responses:
        '200':
          description: Successfully created a new parent

        '400':
          description: Invalid request
  /rentalinstrument/{rentalid}:
    get:
      description: Returns a rental instrument
      parameters:
        - name: rentalid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RentalInstrument"
  /rentalinstrument:
    post:
      description: Lets a user post a new rental instrument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RentalInstrument"

      responses:
        '200':
          description: Successfully created a new rental instrument

        '400':
          description: Invalid request
  /sibling/{siblingid}:
    get:
      description: Returns a sibling
      parameters:
        - name: siblingid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sibling"
  /sibling:
    post:
      description: Lets a user post a new sibling
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sibling"

      responses:
        '200':
          description: Successfully created a new sibling

        '400':
          description: Invalid request
  /userapplication/{applicationid}:
    get:
      description: Returns a user application
      parameters:
        - name: applicationid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserApplication"
  /userapplication:
    post:
      description: Lets a user post a new user application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserApplication"

      responses:
        '200':
          description: Successfully created a new user application

        '400':
          description: Invalid request
  /userinstrument/{instrumentid}:
    get:
      description: Returns a user instrument
      parameters:
        - name: instrumentid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInstrument"
  /userinstrument:
    post:
      description: Lets a user post a new user instrument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInstrument"

      responses:
        '200':
          description: Successfully created a new user instrument

        '400':
          description: Invalid request
  /userpayment/{paymentid}:
    get:
      description: Returns a user payment
      parameters:
        - name: paymentid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPayment"
  /userpayment:
    post:
      description: Lets a user post a new user payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPayment"

      responses:
        '200':
          description: Successfully created a new user payment

        '400':
          description: Invalid request


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        personNumber:
          type: string
        name:
          type: string
        age:
          type: integer
        address:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
    Booking:
      type: object
      properties:
        id:
          type: integer
        startTime:
          type: string
        endTime:
          type: string
        lessonId:
          type: integer
        studentId:
          type: integer
        instructorId:
          type: integer
    InstrumentType:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
    Lease:
      type: object
      properties:
        id:
          type: integer
        startTime:
          type: string
        endTime:
          type: string
        rentalInstrumentId:
          type: integer
        studentId:
          type: integer
    Lesson:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        level:
          type: string
        minParticipants:
          type: integer
        maxParticipants:
          type: integer
        type:
          type: string
        genre:
          type: string
    Parent:
      type: object
      properties:
        studentId:
          type: integer
        parentId:
          type: integer
    RentalInstrument:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        serialNumber:
          type: string
        instrumentTypeId:
          type: integer
    Sibling:
      type: object
      properties:
        studentIdOne:
          type: integer
        studentIdTwo:
          type: integer
    UserApplication:
      type: object
      properties:
        id:
          type: integer
        letter:
          type: string
        instrumentTypeId:
          type: integer
        userId:
          type: integer
    UserInstrument:
      type: object
      properties:
        id:
          type: integer
        instrumentTypeId:
          type: integer
    UserPayment:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        amount:
          type: integer
        currency:
          type: string
        userid:
          type: integer