openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
servers:
  - url: https://soundgood.music/
paths:
  /user:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response
    put:
      description: ""
      parameters: []
      responses:
        "200":
          description: "OK"